local M = {}
local u = require("oz.mappings.util")
local util = require("oz.util")

function M.compile_init(config)
	vim.api.nvim_create_autocmd("FileType", {
		pattern = "compilation",
		callback = function(event)
			-- compilation to term
			util.Map("n", config.mappings.open_in_oz_term, function()
				vim.cmd("CompileInterrupt")
				vim.cmd("close")
				u.cmd_func("Term")
			end, { buffer = event.buf, silent = true, desc = "open in oz_term" })

			-- show keymaps
			util.Map("n", config.mappings.show_keybinds, function()
				util.Show_buf_keymaps({ subtext = { "~ generated by oz" } })
			end, { buffer = event.buf, silent = true, desc = "show all keymaps" })
		end,
	})
end

return M
