local M = {}
local term = require("oz.term")
local util = require("oz.util")
local p = require("oz.caching")
local oil = require("oil")
local json_name = "oilcmd"

local function escape_spaces(s)
	return (s:gsub(" ", "\\ "))
end

local function get_cur_entry(short)
	local cursor = oil.get_cursor_entry()
	local name = cursor.parsed_name or cursor.name

	if short then
		return escape_spaces(name)
	end

	local cwd = oil.get_current_dir()
	local suffix = cursor.type == "directory" and "/" or ""
	local full = table.concat({ cwd, name, suffix }, "")

	return escape_spaces(full)
end

-- get the splitted cmd for cur entry execution
local function split_input(input, middle, splitter)
	local escaped_delimiter = splitter:gsub("[%^%$%(%)%%%.%[%]%*%+%-%?]", "%%%1")
	local pos = input:find(escaped_delimiter)

	if pos then
		local pre_dollar = input:sub(1, pos - 1)
		local post_dollar = input:sub(pos + 1)
		return pre_dollar .. " " .. middle .. " " .. post_dollar
	else
		return input .. " " .. middle
	end
end

-- all the oil specific mappings initialisation
local function oil_buf_mappings(config, g_mappings)
	local term_k = config.mappings.term == "<global>" and g_mappings.Term or config.mappings.term

	if term_k then
		vim.keymap.set("n", term_k, function()
			local oil_cwd = oil.get_current_dir()
			local cmd = p.get_data(oil_cwd, json_name) or ""
			local input = util.UserInput(":Term ", cmd)
			if input then
				if cmd ~= input then
					p.set_data(oil_cwd, input, json_name)
				end
				term.run_in_term(input, oil_cwd)
			end
		end, { buffer = 0, silent = true, desc = "run cmd in this dir with oz_term" })
	end

	-- open compile_mode
	local compile_k = config.mappings.compile == "<global>" and g_mappings.Compile or config.mappings.compile

	if compile_k then
		vim.keymap.set("n", compile_k, function()
			local oil_cwd = oil.get_current_dir()
			vim.g.compilation_directory = oil_cwd
			local cmd = p.get_data(oil_cwd, json_name) or ""
			local input = util.UserInput(":Compile ", cmd)
			if input then
				if cmd ~= input then
					p.set_data(oil_cwd, input, json_name)
				end
				vim.cmd("Compile " .. input)
			end
		end, { buffer = 0, silent = true, desc = "run cmd in this dir with compile_mode" })
	end

	if config.mappings.entry_exec then
		vim.keymap.set("n", config.mappings.entry_exec, function()
			local oil_cwd = oil.get_current_dir()
			local input = util.UserInput("Command:", nil, "shellcmd")

			if input and input ~= "" then
				local cmd = config.entry_exec.use_fullpath
						and split_input(input, get_cur_entry(), config.entry_exec.tail_prefix)
					or split_input(input, get_cur_entry(true), config.entry_exec.tail_prefix)

				if config.entry_exec.method == "background" then
					util.ShellCmd(cmd, function()
						util.echoprint("oz(oil): cmd executed successfully!", "MoreMsg")
						vim.defer_fn(function()
							require("oil.actions").refresh.callback()
						end, 700)
					end, function()
						util.echoprint("oz(oil): cmd execution return error!", "ErrorMsg")
					end)
				elseif config.entry_exec.method == "term" then
					term.run_in_term(cmd, oil_cwd)
				end
			end
		end, { buffer = 0, silent = true, desc = "execute cmd on current cursor entry" })
	end

	-- show keymaps
	if config.mappings.show_keybinds then
		vim.keymap.set("n", config.mappings.show_keybinds, function()
			util.show_maps({
				subtext = { "~ generated by oz" },
			})
		end, { buffer = 0, silent = true, desc = "show all keymaps" })
	end
end

-- oil init
function M.oil_init(config, g_mappings)
	-- oil buffer specific mappings
	oil_buf_mappings(config, g_mappings)
end

return M
